---
# defaults file for hardening


# 1.4.1 Ensure permissions on bootloader config are not overridden
protect_bootloader_permissions: true
## 1.4.2 Ensure bootloader password is set (using grub): default is no
set_bootloader_credentials: no
### Update the default bootloader user and password
bootloader_credentials: { user: "root", password: "b00tl04derPwd" }
# 1.4.3 Ensure authentication required for single user mode
set_root_password: yes
root_password: r00tP4ssw0rd
# Section 4 Settings
## Ensure rsyslog is configured to send logs to a remote log host
remoteSyslog:
  enable: false
  host: 192.168.2.100
  port: 514
  protocol: tcp
logrotate_policy: "daily"
## auditd config
architecture: "x86_64"
admin_space_left_action: halt
max_log_file_action: keep_logs
max_log_file: 10
backlog_limit: "8192"
space_left_action: email
action_mail_acct: root
grub_backlog_limit: 8192
# 5.3.7 Ensure SSH MaxAuthTries is set to 4 or less
max_auth_tries: 4
## 5.3.21 Ensure SSH MaxStartups is configured
ssh_max_startups: "10:30:100"
# Section 5 PAM config
usersAllowedToSuAccess:
  - root
adminGroup: root

## 5.4.1.1 Ensure password expiration is 365 days or less
pass_expire_in_days: 300
pass_warn_age: 7
pass_min_days: 1
## 5.4.1.1 Ensure password expiration is 365 days or less
list_of_os_users:
  - svjtosha 
## 5.4.1.4 Ensure inactive password lock is 30 days or less
##Note: A value of -1 would disable this setting
account_inactive: 30
## 5.4.5 Ensure default user shell timeout is 900 seconds or less
shell_timeout_sec: 900
## 5.5.4 Ensure default user umask is 027 or more restrictive
umask_value: "027" # Adds the option to declare the umask preferred value, with 027 as default
## In some particular use cases (e.g. installing and using new python packages after 
## hardening), it is required that umask permissions were not as strict as 
## 027, because the system will not be able to run the newer python packages. 
## In those cases, it would be better to be able to set the 
## default umask permissions needed for the use case.
fix_command_not_found: false # Adds a change to /etc/apt/apt.conf.d/50command-not-found to fix a known issue.
## Note: Issue link for fix_command_not_found https://bugs.launchpad.net/command-not-found/+bug/1824000/
