---
# tasks file for deploy-wordpress
- name: Deploy Wordpress chart from local path
  kubernetes.core.helm:
    name: Deploy WP
    chart_ref: /home/svjtosha/Documents/final-task/ansible/roles/deploy-wordpress/files/
    release_namespace: default



 