---
# tasks file for deploy-wordpress

- name: Creates directory .kube/
  ansible.builtin.file:
    path: .kube/
    state: directory

- name: Copy admin.conf
  ansible.builtin.copy:
      remote_src: yes
      src: /etc/kubernetes/admin.conf
      dest: .kube/config

- name: Verify Permissions on .kube/config
  ansible.builtin.file:
    path: .kube/config
    mode: '0777'

- name: Install helm with option --classic
  community.general.snap:
    name: helm
    classic: true

- name: Copy helm chart
  ansible.builtin.copy:
      src: wordpress/
      dest: wordpress/
      backup: yes

- name: Verify Permissions on wordpress/
  ansible.builtin.file:
    path: wordpress/
    mode: '0777'

- name: Deploy
  kubernetes.core.helm:
    name: wordpress
    chart_ref: wordpress/
    release_namespace: default



 