---
# tasks file for deploy-wordpress

- name: Creates directory .kube/
  ansible.builtin.file:
    path: .kube/
    state: directory

- name: Copy admin.conf
  ansible.builtin.copy:
      remote_src: yes
      src: /etc/kubernetes/admin.conf
      dest: .kube/config

- name: Verify Permissions on .kube/config
  ansible.builtin.file:
    path: .kube/config
    mode: '0777'

- name: Install helm with option --classic
  community.general.snap:
    name: helm
    classic: true




 